name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write  # Required for trusted publishing
      contents: read
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build wheel setuptools twine
    
    - name: Build package
      run: python -m build
    
    - name: Check distribution
      run: |
        twine check dist/*
        ls -lah dist/
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
